import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';
import type { Language } from '../types/types';

// ─── Translation Dictionary ─────────────────────────────────────────
const dict: Record<string, Record<Language, string>> = {
  // Nav
  'nav.buy': { en: 'Buy', vi: 'Mua' },
  'nav.rent': { en: 'Rent', vi: 'Thuê' },
  'nav.sell': { en: 'Sell', vi: 'Bán' },
  'nav.projects': { en: 'Projects', vi: 'Dự án' },
  'nav.mortgage': { en: 'Get a mortgage', vi: 'Vay mua nhà' },
  'nav.agent': { en: 'Find an agent', vi: 'Tìm môi giới' },
  'nav.manage': { en: 'Manage rentals', vi: 'Quản lý cho thuê' },
  'nav.advertise': { en: 'Advertise', vi: 'Quảng cáo' },
  'nav.help': { en: 'Get help', vi: 'Hỗ trợ' },
  'nav.signin': { en: 'Sign in', vi: 'Đăng nhập' },
  'nav.signout': { en: 'Sign out', vi: 'Đăng xuất' },
  'nav.dashboard': { en: 'Dashboard', vi: 'Bảng điều khiển' },
  'nav.favorites': { en: 'My Favorites', vi: 'Yêu thích' },
  'nav.post': { en: 'Post Property', vi: 'Đăng tin' },
  'nav.search': { en: 'Search', vi: 'Tìm kiếm' },
  'nav.updates': { en: 'Updates', vi: 'Cập nhật' },
  'nav.homeLoans': { en: 'Home Loans', vi: 'Vay mua nhà' },
  'nav.inquiries': { en: 'Inquiries', vi: 'Yêu cầu' },

  // Filters
  'filter.price': { en: 'Price', vi: 'Giá' },
  'filter.beds': { en: 'Beds & Baths', vi: 'Phòng ngủ & Tắm' },
  'filter.type': { en: 'Home Type', vi: 'Loại nhà' },
  'filter.area': { en: 'Area', vi: 'Diện tích' },
  'filter.anyPrice': { en: 'Any Price', vi: 'Mọi giá' },
  'filter.anyType': { en: 'Any Type', vi: 'Mọi loại' },
  'filter.clearAll': { en: 'Clear all', vi: 'Xóa bộ lọc' },
  'filter.search': { en: 'Search', vi: 'Tìm kiếm' },
  'filter.results': { en: 'results', vi: 'kết quả' },
  'filter.result': { en: 'result', vi: 'kết quả' },
  'filter.bedrooms': { en: 'Bedrooms', vi: 'Phòng ngủ' },
  'filter.bathrooms': { en: 'Bathrooms', vi: 'Phòng tắm' },
  'filter.minArea': { en: 'Min sqft', vi: 'Diện tích tối thiểu' },
  'filter.maxArea': { en: 'Max sqft', vi: 'Diện tích tối đa' },
  'filter.apply': { en: 'Apply', vi: 'Áp dụng' },
  'filter.searchPlaceholder': { en: 'Search by city, state, or address', vi: 'Tìm theo thành phố, tỉnh hoặc địa chỉ' },

  // Property
  'prop.forSale': { en: 'For Sale', vi: 'Bán' },
  'prop.forRent': { en: 'For Rent', vi: 'Cho thuê' },
  'prop.bds': { en: 'bds', vi: 'PN' },
  'prop.ba': { en: 'ba', vi: 'PT' },
  'prop.sqft': { en: 'sqft', vi: 'm²' },
  'prop.vip': { en: 'VIP', vi: 'VIP' },
  'prop.newListing': { en: 'New Listing', vi: 'Tin mới' },

  // Buttons
  'btn.compare': { en: 'Compare', vi: 'So sánh' },
  'btn.report': { en: 'Report', vi: 'Báo cáo' },
  'btn.schedule': { en: 'Schedule Viewing', vi: 'Đặt lịch xem' },
  'btn.aiGenerate': { en: '✨ AI Generate Description', vi: '✨ AI viết mô tả' },
  'btn.publish': { en: 'Publish Listing', vi: 'Đăng tin' },
  'btn.save': { en: 'Save', vi: 'Lưu' },
  'btn.cancel': { en: 'Cancel', vi: 'Hủy' },
  'btn.submit': { en: 'Submit', vi: 'Gửi' },
  'btn.viewDetails': { en: 'View Details', vi: 'Xem chi tiết' },
  'btn.clearFilters': { en: 'Clear All Filters', vi: 'Xóa tất cả bộ lọc' },
  'btn.whatsapp': { en: 'Chat on WhatsApp', vi: 'Nhắn WhatsApp' },

  // Status
  'status.active': { en: 'Active', vi: 'Đang hoạt động' },
  'status.pending': { en: 'Pending', vi: 'Chờ duyệt' },
  'status.expired': { en: 'Expired', vi: 'Hết hạn' },
  'status.hidden': { en: 'Hidden', vi: 'Đã ẩn' },
  'status.expiringSoon': { en: 'Expiring Soon', vi: 'Sắp hết hạn' },
  'status.confirmed': { en: 'Confirmed', vi: 'Đã xác nhận' },
  'status.cancelled': { en: 'Cancelled', vi: 'Đã hủy' },
  'status.reviewed': { en: 'Reviewed', vi: 'Đã xem' },
  'status.resolved': { en: 'Resolved', vi: 'Đã xử lý' },

  // Common
  'common.noResults': { en: 'No results found', vi: 'Không tìm thấy kết quả' },
  'common.loading': { en: 'Loading...', vi: 'Đang tải...' },
  'common.error': { en: 'An error occurred', vi: 'Đã xảy ra lỗi' },
  'common.success': { en: 'Success!', vi: 'Thành công!' },
  'common.noHomes': { en: 'No homes found', vi: 'Không tìm thấy bất động sản' },

  // Pages
  'page.homesSale': { en: 'Homes for Sale', vi: 'Nhà bán' },
  'page.homesRent': { en: 'Homes for Rent', vi: 'Nhà cho thuê' },
  'page.projects': { en: 'Real Estate Projects', vi: 'Dự án bất động sản' },
  'page.compare': { en: 'Compare Properties', vi: 'So sánh bất động sản' },
  'page.postProperty': { en: 'Post a Property', vi: 'Đăng tin bất động sản' },
  'page.admin': { en: 'Admin Panel', vi: 'Quản trị' },
  'page.dashboard': { en: 'Dashboard', vi: 'Bảng điều khiển' },

  // Report
  'report.title': { en: 'Report this listing', vi: 'Báo cáo tin đăng này' },
  'report.reason': { en: 'Reason', vi: 'Lý do' },
  'report.spam': { en: 'Spam', vi: 'Spam' },
  'report.incorrect': { en: 'Incorrect information', vi: 'Thông tin sai' },
  'report.scam': { en: 'Suspected scam', vi: 'Nghi lừa đảo' },
  'report.duplicate': { en: 'Duplicate listing', vi: 'Tin trùng lặp' },
  'report.other': { en: 'Other', vi: 'Khác' },
  'report.description': { en: 'Description', vi: 'Mô tả' },
  'report.success': { en: 'Report submitted successfully', vi: 'Báo cáo đã được gửi' },

  // Schedule
  'schedule.title': { en: 'Schedule a Viewing', vi: 'Đặt lịch xem nhà' },
  'schedule.name': { en: 'Your Name', vi: 'Họ tên' },
  'schedule.phone': { en: 'Phone', vi: 'Số điện thoại' },
  'schedule.email': { en: 'Email', vi: 'Email' },
  'schedule.date': { en: 'Preferred Date', vi: 'Ngày mong muốn' },
  'schedule.time': { en: 'Preferred Time', vi: 'Giờ mong muốn' },
  'schedule.message': { en: 'Message (optional)', vi: 'Lời nhắn (tùy chọn)' },
  'schedule.success': { en: 'Viewing scheduled!', vi: 'Đã đặt lịch thành công!' },

  // Compare
  'compare.empty': { en: 'No properties selected for comparison', vi: 'Chưa chọn bất động sản để so sánh' },
  'compare.add': { en: 'Add to Compare', vi: 'Thêm so sánh' },
  'compare.remove': { en: 'Remove', vi: 'Bỏ' },
  'compare.max': { en: 'Maximum 3 properties', vi: 'Tối đa 3 bất động sản' },
  'compare.view': { en: 'View Comparison', vi: 'Xem so sánh' },

  // VIP
  'vip.label': { en: 'VIP Listing', vi: 'Tin VIP' },
  'vip.normal': { en: 'Normal Listing', vi: 'Tin thường' },
  'vip.badge': { en: 'VIP', vi: 'VIP' },
  'vip.duration30': { en: '30-day VIP', vi: 'VIP 30 ngày' },
  'vip.duration15': { en: '15-day listing', vi: 'Tin 15 ngày' },

  // Post Property Page
  'post.title': { en: 'Post a Property', vi: 'Đăng tin bất động sản' },
  'post.subtitle': { en: 'List your property on So Do Van Phuc and reach thousands of qualified buyers.', vi: 'Đăng tin trên So Do Van Phuc để tiếp cận hàng nghìn khách hàng tiềm năng.' },
  'post.basicInfo': { en: 'Basic Information', vi: 'Thông tin cơ bản' },
  'post.priceSpecs': { en: 'Price & Specifications', vi: 'Giá & Thông số' },
  'post.location': { en: 'Location', vi: 'Vị trí' },
  'post.photos': { en: 'Photos', vi: 'Hình ảnh' },
  'post.description': { en: 'Description', vi: 'Mô tả' },
  'post.video': { en: 'Video', vi: 'Video' },
  'post.contactInfo': { en: 'Listing Contact', vi: 'Liên hệ riêng của tin đăng' },
  'post.formTitle': { en: 'Title', vi: 'Tiêu đề' },
  'post.titlePlaceholder': { en: 'e.g. Stunning Oceanfront Estate', vi: 'VD: Stunning Oceanfront Estate' },
  'post.propertyType': { en: 'Property Type', vi: 'Loại bất động sản' },
  'post.listingType': { en: 'Listing Type', vi: 'Hình thức' },
  'post.listingPlan': { en: 'Listing Plan', vi: 'Gói đăng tin' },
  'post.listingDuration': { en: 'Listing Duration', vi: 'Thời hạn đăng' },
  'post.singleFamily': { en: 'Single Family', vi: 'Nhà riêng' },
  'post.condo': { en: 'Condo', vi: 'Căn hộ' },
  'post.townhouse': { en: 'Townhouse', vi: 'Nhà phố' },
  'post.villa': { en: 'Villa', vi: 'Biệt thự' },
  'post.land': { en: 'Land', vi: 'Đất nền' },
  'post.commercial': { en: 'Commercial', vi: 'Thương mại' },
  'post.forSale': { en: 'For Sale', vi: 'Bán' },
  'post.forRent': { en: 'For Rent', vi: 'Cho thuê' },
  'post.free': { en: 'Free', vi: 'Miễn phí' },
  'post.pro': { en: 'Pro', vi: 'Pro' },
  'post.freeDesc': { en: 'Free listing - max 10 posts per account', vi: 'Miễn phí - tối đa 10 tin/tài khoản' },
  'post.price': { en: 'Price ($)', vi: 'Giá (USD)' },
  'post.pricePlaceholder': { en: 'e.g. 450000', vi: 'VD: 450000' },
  'post.bedrooms': { en: 'Bedrooms', vi: 'Phòng ngủ' },
  'post.bathrooms': { en: 'Bathrooms', vi: 'Phòng tắm' },
  'post.sqft': { en: 'Square Feet', vi: 'Diện tích (m²)' },
  'post.address': { en: 'Address', vi: 'Địa chỉ' },
  'post.addressPlaceholder': { en: 'e.g. 1234 Pacific Coast Hwy', vi: 'VD: 1234 Pacific Coast Hwy' },
  'post.city': { en: 'City', vi: 'Thành phố' },
  'post.cityPlaceholder': { en: 'e.g. Malibu', vi: 'VD: Malibu' },
  'post.state': { en: 'State', vi: 'Tỉnh/Thành' },
  'post.statePlaceholder': { en: 'e.g. California', vi: 'VD: California' },
  'post.zip': { en: 'ZIP Code', vi: 'Mã bưu chính' },
  'post.zipPlaceholder': { en: 'e.g. 90265', vi: 'VD: 90265' },
  'post.mapPreview': { en: 'Map Preview', vi: 'Xem trước bản đồ' },
  'post.mapDragHint': { en: 'Click or drag the pin to set the exact location. The map updates automatically when you type an address.', vi: 'Nhấn hoặc kéo ghim để đặt vị trí chính xác. Bản đồ tự cập nhật khi bạn nhập địa chỉ.' },
  'post.customizePin': { en: '📍 Customize Pin', vi: '📍 Tùy chỉnh vị trí' },
  'post.pinLocation': { en: 'Pin Location', vi: 'Ghim vị trí' },
  'post.backToPreview': { en: 'Back', vi: 'Quay lại' },
  'post.descLabel': { en: 'Description', vi: 'Mô tả chi tiết' },
  'post.descPlaceholder': { en: 'Describe your property - highlight key features, recent updates, and neighborhood benefits...', vi: 'Mô tả bất động sản - nêu bật đặc điểm nổi bật, tiện ích xung quanh...' },
  'post.uploadVideo': { en: 'Upload video from device', vi: 'Tải video từ thiết bị' },
  'post.importLinks': { en: 'Import links', vi: 'Liên kết ngoài' },
  'post.contactName': { en: 'Owner / agent name', vi: 'Tên chủ nhà / môi giới' },
  'post.contactPhone': { en: 'Call phone', vi: 'Số điện thoại gọi' },
  'post.contactEmail': { en: 'Listing email', vi: 'Email của tin đăng' },
  'post.contactWhatsapp': { en: 'Listing WhatsApp', vi: 'WhatsApp của tin đăng' },
  'post.contactWhatsappPlaceholder': { en: 'Phone number or https://wa.me/...', vi: 'Số WhatsApp hoặc https://wa.me/...' },
  'post.submitListing': { en: 'Submit Listing', vi: 'Đăng tin' },
  'post.submitting': { en: 'Submitting...', vi: 'Đang gửi...' },
  'post.submissionFailed': { en: 'Submission Failed', vi: 'Gửi thất bại' },
  'post.addMore': { en: 'Add more', vi: 'Thêm ảnh' },
  'post.previewOnly': { en: 'Preview only', vi: 'Xem trước' },
  'post.of': { en: 'of', vi: '/' },
  'post.payment': { en: 'Payment', vi: 'Thanh toán' },
  'post.paymentComplete': { en: 'Payment complete', vi: 'Đã thanh toán' },
  'post.paymentRequired': { en: 'Required before posting', vi: 'Cần thanh toán trước khi đăng' },
  'post.paymentSuccess': { en: 'Payment Successful', vi: 'Thanh toán thành công' },
  'post.paymentExplain': { en: 'You need to pay {price} to publish your Pro listing for {days} days. Pro listings get priority placement and VIP badge.', vi: 'Bạn cần thanh toán {price} để đăng tin Pro trong {days} ngày. Tin Pro được ưu tiên hiển thị và có huy hiệu VIP.' },
  'post.cardVerification': { en: 'Card Verification', vi: 'Xác minh thẻ' },
  'post.oneTimeOnly': { en: 'One-time only', vi: 'Chỉ một lần' },
  'post.cardVerified': { en: 'Card verified', vi: 'Thẻ đã xác minh' },
  'post.cardVerificationIntro': { en: 'Add a payment method to start posting free listings. You will not be charged.', vi: 'Thêm phương thức thanh toán để bắt đầu đăng tin miễn phí. Bạn sẽ không bị tính phí.' },
  'post.verifyCard': { en: 'Verify Card', vi: 'Xác minh thẻ' },
  'post.verifyCardNote': { en: 'Add your PayPal or card to verify your account. No charge will be applied.', vi: 'Thêm PayPal hoặc thẻ để xác minh tài khoản. Không tính phí.' },
  'post.freePostsRemaining': { en: 'You have {count} of {limit} free posts remaining', vi: 'Bạn còn {count} trong {limit} tin miễn phí' },
  'post.month': { en: 'month', vi: 'tháng' },
  'post.monthFreeBonus': { en: '1 month free', vi: 'tặng 1 tháng' },
  'post.successTitle': { en: 'Listing Submitted!', vi: 'Đăng tin thành công!' },
  'post.successMsg': { en: 'Your property listing has been submitted successfully.', vi: 'Tin đăng của bạn đã được gửi thành công.' },
  'post.goToDashboard': { en: 'Go to Dashboard', vi: 'Về trang chủ' },
  'post.browseListings': { en: 'Browse Listings', vi: 'Xem tin đăng' },
  'post.demoNote': { en: 'Media upload:', vi: 'Tải ảnh:' },
  'post.days': { en: 'days', vi: 'ngày' },

  // Validation errors
  'err.required': { en: 'is required', vi: 'là bắt buộc' },
  'err.titleRequired': { en: 'Title is required', vi: 'Tiêu đề là bắt buộc' },
  'err.priceRequired': { en: 'Price is required', vi: 'Giá là bắt buộc' },
  'err.priceNumber': { en: 'Price must be a number', vi: 'Giá phải là số' },
  'err.bedroomsRequired': { en: 'Bedrooms is required', vi: 'Số phòng ngủ là bắt buộc' },
  'err.bathroomsRequired': { en: 'Bathrooms is required', vi: 'Số phòng tắm là bắt buộc' },
  'err.mustBeNumber': { en: 'Must be a number', vi: 'Phải là số' },
  'err.addressRequired': { en: 'Address is required', vi: 'Địa chỉ là bắt buộc' },
  'err.cityRequired': { en: 'City is required', vi: 'Thành phố là bắt buộc' },
  'err.stateRequired': { en: 'State is required', vi: 'Tỉnh/thành là bắt buộc' },
  'err.invalidEmail': { en: 'Please enter a valid email address', vi: 'Vui lòng nhập email hợp lệ' },
  'err.invalidVideo': { en: 'Please select a valid video file', vi: 'Vui lòng chọn file video hợp lệ' },
  'err.paypalRequired': { en: 'Please complete PayPal payment before posting your Pro listing.', vi: 'Vui lòng thanh toán PayPal trước khi đăng tin Pro.' },
  'err.cardVerificationRequired': { en: 'Please verify a card before posting your free listing.', vi: 'Vui lòng xác minh thẻ trước khi đăng tin miễn phí.' },
  'err.freePostLimitReached': { en: 'You have used all 10 free posts. Please choose Pro to continue posting.', vi: 'Bạn đã dùng hết 10 tin miễn phí. Vui lòng chọn Pro để tiếp tục đăng tin.' },

  // Dashboard
  'dash.savedHomes': { en: 'Saved Homes', vi: 'Đã lưu' },
  'dash.myListings': { en: 'My Listings', vi: 'Tin của tôi' },
  'dash.inquiries': { en: 'Inquiries', vi: 'Yêu cầu' },
  'dash.profile': { en: 'Profile', vi: 'Hồ sơ' },
  'dash.profileComplete': { en: 'Profile Complete', vi: 'Hồ sơ hoàn chỉnh' },
  'dash.recentActivity': { en: 'Recent Activity', vi: 'Hoạt động gần đây' },
  'dash.scheduledViewings': { en: 'Scheduled Viewings', vi: 'Lịch xem nhà' },
  'dash.savedProperties': { en: 'Saved Properties', vi: 'BĐS đã lưu' },
  'dash.yourListings': { en: 'Your Listings', vi: 'Tin đăng của bạn' },
  'dash.changeAvatar': { en: 'Change Avatar', vi: 'Đổi ảnh đại diện' },
  'dash.noSchedules': { en: 'No scheduled viewings yet', vi: 'Chưa có lịch xem nhà' },
  'dash.noSaved': { en: 'No saved properties yet', vi: 'Chưa lưu bất động sản nào' },
  'dash.noListings': { en: 'No listings yet', vi: 'Chưa có tin đăng' },
  'dash.welcomeBack': { en: 'Welcome back, {name}', vi: 'Chào mừng trở lại, {name}' },
  'dash.overview': { en: "Here's an overview of your So Do Van Phuc activity.", vi: 'Đây là tổng quan hoạt động So Do Van Phuc của bạn.' },
  'dash.signInPrompt': { en: 'Sign in to access your personalized dashboard', vi: 'Đăng nhập để xem bảng điều khiển cá nhân' },
  'dash.signInPromptDesc': { en: 'Save homes, track listings, and manage your profile all in one place.', vi: 'Lưu nhà, theo dõi tin đăng và quản lý hồ sơ tại một nơi.' },
  'dash.expiryNotice': { en: 'Listing Expiry Notice', vi: 'Thông báo hết hạn tin đăng' },
  'dash.expiryNoticeDesc': { en: '{count} of your listings are expiring soon or already expired. Renew them to keep them visible.', vi: '{count} tin đăng của bạn sắp hết hạn hoặc đã hết hạn. Gia hạn để tiếp tục hiển thị.' },
  'dash.manageListings': { en: 'Manage Listings', vi: 'Quản lý tin đăng' },
  'dash.viewAll': { en: 'View All', vi: 'Xem tất cả' },
  'dash.findHomes': { en: 'Find Homes', vi: 'Tìm nhà' },
  'dash.manage': { en: 'Manage', vi: 'Quản lý' },
  'dash.inquiriesReceived': { en: 'Inquiries Received', vi: 'Yêu cầu tư vấn đã nhận' },
  'dash.replyEmail': { en: 'Reply via Email', vi: 'Trả lời qua Email' },
  'dash.total': { en: '{count} total', vi: 'Tổng {count}' },
  'dash.guest': { en: 'Guest', vi: 'Khách' },
  'dash.activitySaved': { en: '{count} saved homes', vi: '{count} nhà đã lưu' },
  'dash.activityListings': { en: '{count} active listings', vi: '{count} tin đang hoạt động' },
  'dash.activityInquiries': { en: '{count} inquiries received', vi: '{count} yêu cầu đã nhận' },
  'dash.checkAdminDetails': { en: 'Check your admin panel for details', vi: 'Xem chi tiết trong bảng quản trị' },
  'dash.expired': { en: 'Expired', vi: 'Hết hạn' },
  'dash.expiringIn': { en: 'Expiring in {days}d', vi: 'Hết hạn sau {days} ngày' },
  'dash.expiresIn': { en: 'Expires in {days}d', vi: 'Còn {days} ngày' },
  'dash.paid': { en: 'Paid', vi: 'Đã thanh toán' },
  'dash.atTime': { en: '{date} at {time}', vi: '{date} lúc {time}' },
  'dash.browseProperties': { en: 'Browse Properties', vi: 'Xem bất động sản' },
  'dash.postProperty': { en: 'Post a Property', vi: 'Đăng bất động sản' },
  'dash.browseListings': { en: 'Browse Listings', vi: 'Xem tin đăng' },

  // Auth
  'auth.signIn': { en: 'Sign in', vi: 'Đăng nhập' },
  'auth.signInDesc': { en: 'Access So Do Van Phuc operations', vi: 'Vào hệ thống Sổ Đỏ Vạn Phúc để quản lý nguồn nhà và khách hàng.' },
  'auth.register': { en: 'Create Account', vi: 'Tạo tài khoản' },
  'auth.registerDesc': { en: 'Join So Do Van Phuc today', vi: 'Tham gia So Do Van Phuc ngay' },
  'auth.email': { en: 'Email', vi: 'Email' },
  'auth.password': { en: 'Password', vi: 'Mật khẩu' },
  'auth.confirmPassword': { en: 'Confirm Password', vi: 'Xác nhận mật khẩu' },
  'auth.fullName': { en: 'Full Name', vi: 'Họ và tên' },
  'auth.forgotPassword': { en: 'Forgot password?', vi: 'Quên mật khẩu?' },
  'auth.noAccount': { en: "Don't have an account?", vi: 'Chưa có tài khoản?' },
  'auth.hasAccount': { en: 'Already have an account?', vi: 'Đã có tài khoản?' },
  'auth.creatingAccount': { en: 'Creating Account...', vi: 'Đang tạo tài khoản...' },

  // Property Detail
  'detail.description': { en: 'Description', vi: 'Mô tả' },
  'detail.features': { en: 'Key Features', vi: 'Đặc điểm nổi bật' },
  'detail.contactAgent': { en: 'Contact Agent', vi: 'Liên hệ môi giới' },
  'detail.similarHomes': { en: 'Similar Homes', vi: 'BĐS tương tự' },
  'detail.overview': { en: 'Overview', vi: 'Tổng quan' },
  'detail.viewCount': { en: 'views', vi: 'lượt xem' },

  // Favorites
  'fav.title': { en: 'My Favorites', vi: 'Yêu thích của tôi' },
  'fav.empty': { en: 'No favorites yet', vi: 'Chưa có mục yêu thích' },
  'fav.emptyDesc': { en: 'Save properties you love to see them here', vi: 'Lưu bất động sản yêu thích để xem tại đây' },

  // Inquiries Page
  'inquiries.desc': { en: 'Manage inquiries submitted by clients through listing details and contact forms.', vi: 'Quản lý yêu cầu từ khách hàng qua trang chi tiết và liên hệ.' },
  'inquiries.received': { en: 'Received', vi: 'Ngày nhận' },
  'inquiries.propertyType': { en: 'Property / Type', vi: 'BĐS / Loại' },
  'inquiries.client': { en: 'Client', vi: 'Khách hàng' },
  'inquiries.message': { en: 'Message', vi: 'Tin nhắn' },
  'inquiries.status': { en: 'Status', vi: 'Trạng thái' },
  'inquiries.actions': { en: 'Actions', vi: 'Thao tác' },
  'inquiries.new': { en: 'New', vi: 'Mới' },
  'inquiries.read': { en: 'Read', vi: 'Đã đọc' },
  'inquiries.markRead': { en: 'Mark as Read', vi: 'Đánh dấu đã đọc' },
  'inquiries.markNew': { en: 'Mark as New', vi: 'Đánh dấu mới' },
  'inquiries.markUnread': { en: 'Mark Unread', vi: 'Chưa đọc' },
  'inquiries.delete': { en: 'Delete', vi: 'Xóa' },
  'inquiries.confirmDelete': { en: 'Are you sure you want to delete this inquiry?', vi: 'Bạn có chắc muốn xóa yêu cầu này?' },
  'inquiries.noFound': { en: 'No Inquiries Found', vi: 'Chưa có yêu cầu nào' },
  'inquiries.empty': { en: 'When users fill out contact forms on the listings detail pages or the general contact page, their messages will display here.', vi: 'Khi người dùng gửi liên hệ từ trang chi tiết hoặc trang liên hệ, tin nhắn sẽ hiện tại đây.' },

  // Listing Page - extra
  'page.homesSaleDesc': { en: 'Explore premium properties across key markets.', vi: 'Khám phá bất động sản cao cấp tại các thị trường trọng điểm.' },
  'page.homesRentDesc': { en: 'Discover quality rental homes in top locations.', vi: 'Tìm nhà cho thuê chất lượng tại các vị trí đắc địa.' },
  'common.viewAll': { en: 'View All', vi: 'Xem tất cả' },
  'common.homesForYou': { en: 'Homes For You', vi: 'Dành cho bạn' },
  'common.homesForYouSub': { en: 'Based on homes you recently viewed', vi: 'Dựa trên những bất động sản bạn đã xem' },
  'btn.browseHomes': { en: 'Browse Homes', vi: 'Xem nhà' },
  'btn.postProperty': { en: 'Post Property', vi: 'Đăng tin' },

  // Contact Page
  'contact.title': { en: 'Contact Us', vi: 'Liên hệ' },
  'contact.subtitle': { en: 'We\'d love to hear from you', vi: 'Chúng tôi rất muốn nghe ý kiến của bạn' },
  'contact.name': { en: 'Your Name', vi: 'Họ và tên' },
  'contact.email': { en: 'Email', vi: 'Email' },
  'contact.phone': { en: 'Phone', vi: 'Số điện thoại' },
  'contact.subject': { en: 'Subject', vi: 'Tiêu đề' },
  'contact.message': { en: 'Message', vi: 'Nội dung' },
  'contact.send': { en: 'Send Message', vi: 'Gửi tin nhắn' },
  'contact.sending': { en: 'Sending...', vi: 'Đang gửi...' },
  'contact.success': { en: 'Message sent successfully!', vi: 'Gửi tin nhắn thành công!' },
  'contact.form_sub': { en: 'Fill out the form below and we\'ll get back to you promptly.', vi: 'Điền form bên dưới, chúng tôi sẽ phản hồi sớm nhất.' },

  // PropertyDetail
  'detail.scheduleViewing': { en: 'Schedule a Viewing', vi: 'Đặt lịch xem nhà' },
  'detail.sendMessage': { en: 'Send Message', vi: 'Gửi tin nhắn' },
  'detail.share': { en: 'Share', vi: 'Chia sẻ' },
  'detail.save': { en: 'Save', vi: 'Lưu' },
  'detail.saved': { en: 'Saved', vi: 'Đã lưu' },
  'detail.beds': { en: 'Beds', vi: 'PN' },
  'detail.baths': { en: 'Baths', vi: 'PT' },


  // Footer
  'footer.about': { en: 'About', vi: 'Giới thiệu' },
  'footer.careers': { en: 'Careers', vi: 'Tuyển dụng' },
  'footer.help': { en: 'Help', vi: 'Trợ giúp' },
  'footer.advertise': { en: 'Advertise', vi: 'Quảng cáo' },
  'footer.terms': { en: 'Terms of use', vi: 'Điều khoản' },
  'footer.privacy': { en: 'Privacy Notice', vi: 'Chính sách riêng tư' },
  'footer.browseHomes': { en: 'Browse Homes', vi: 'Xem nhà' },

  // About Page
  'about.title': { en: 'About So Do Van Phuc', vi: 'Về So Do Van Phuc' },
  'about.subtitle': { en: 'Redefining Real Estate Discovery', vi: 'Đổi mới cách tìm bất động sản' },
  'about.home': { en: 'Home', vi: 'Trang chủ' },
  'about.exploreHomes': { en: 'Explore Homes', vi: 'Khám phá nhà' },
  'about.ourMission': { en: 'Our Mission', vi: 'Sứ mệnh' },
  'about.whyChoose': { en: 'Why Choose Us', vi: 'Tại sao chọn chúng tôi' },

  // Admin Page
  'admin.title': { en: 'Admin Dashboard', vi: 'Quản trị' },
  'admin.listings': { en: 'Listings', vi: 'Tin đăng' },
  'admin.active': { en: 'Active', vi: 'Đang hoạt động' },
  'admin.inactive': { en: 'Inactive', vi: 'Không hoạt động' },
  'admin.expired': { en: 'Expired', vi: 'Hết hạn' },
  'admin.addListing': { en: 'Add Listing', vi: 'Thêm tin' },
  'admin.editListing': { en: 'Edit Listing', vi: 'Sửa tin' },
  'admin.deleteListing': { en: 'Delete Listing', vi: 'Xóa tin' },
  'admin.confirmDelete': { en: 'Are you sure you want to delete this listing?', vi: 'Bạn có chắc muốn xóa tin này?' },
  'admin.save': { en: 'Save', vi: 'Lưu' },
  'admin.cancel': { en: 'Cancel', vi: 'Hủy' },
  'admin.title_label': { en: 'Title', vi: 'Tiêu đề' },
  'admin.description': { en: 'Description', vi: 'Mô tả' },
  'admin.price': { en: 'Price', vi: 'Giá' },
  'admin.status': { en: 'Status', vi: 'Trạng thái' },
  'admin.actions': { en: 'Actions', vi: 'Thao tác' },
  'admin.image': { en: 'Image', vi: 'Ảnh' },
  'admin.property': { en: 'Property', vi: 'Bất động sản' },
  'admin.noListings': { en: 'No listings found', vi: 'Chưa có tin đăng' },
  'admin.sessionExpired': { en: 'Admin session expired. Please login again.', vi: 'Phiên quản trị đã hết hạn. Vui lòng đăng nhập lại.' },

  // Blog Page
  'blog.title': { en: 'Blog', vi: 'Bài viết' },
  'blog.subtitle': { en: 'Latest news and insights', vi: 'Tin tức và kiến thức mới nhất' },
  'blog.readMore': { en: 'Read More', vi: 'Xem thêm' },
  'blog.notFound': { en: 'Post Not Found', vi: 'Không tìm thấy bài viết' },
  'blog.backToBlog': { en: 'Back to Blog', vi: 'Quay lại Blog' },

  // Compare Page
  'compare.title': { en: 'Compare Properties', vi: 'So sánh bất động sản' },
  'compare.subtitle': { en: 'Side by side comparison', vi: 'So sánh chi tiết' },
  'compare.addMore': { en: 'Add more properties to compare', vi: 'Thêm bất động sản để so sánh' },
  'compare.clearAll': { en: 'Clear All', vi: 'Xóa tất cả' },
  'compare.emptySub': { en: 'Add up to 3 properties to compare side by side. Use the compare button on property cards or detail pages.', vi: 'Thêm tối đa 3 bất động sản để so sánh. Dùng nút so sánh trên thẻ hoặc trang chi tiết.' },
  'compare.property': { en: 'Property', vi: 'Bất động sản' },
  'compare.viewDetails': { en: 'View Details', vi: 'Xem chi tiết' },

  // Forgot / Reset Password
  'auth.forgotTitle': { en: 'Forgot Password', vi: 'Quên mật khẩu' },
  'auth.forgotDesc': { en: 'We\'ll send you reset instructions', vi: 'Chúng tôi sẽ gửi hướng dẫn đặt lại mật khẩu' },
  'auth.sendResetLink': { en: 'Send Reset Link', vi: 'Gửi liên kết đặt lại' },
  'auth.sending': { en: 'Sending...', vi: 'Đang gửi...' },
  'auth.backToSignIn': { en: 'Back to Sign In', vi: 'Quay lại đăng nhập' },
  'auth.resetTitle': { en: 'Reset Password', vi: 'Đặt lại mật khẩu' },
  'auth.resetDesc': { en: 'Create a new password for your account', vi: 'Tạo mật khẩu mới cho tài khoản' },
  'auth.newPassword': { en: 'New Password', vi: 'Mật khẩu mới' },
  'auth.resetPassword': { en: 'Reset Password', vi: 'Đặt lại mật khẩu' },
  'auth.resetting': { en: 'Resetting...', vi: 'Đang đặt lại...' },
  'auth.changePassword': { en: 'Change Password', vi: 'Đổi mật khẩu' },
  'auth.currentPassword': { en: 'Current Password', vi: 'Mật khẩu hiện tại' },
  'auth.changingPassword': { en: 'Changing...', vi: 'Đang đổi...' },

  // Inbox Page
  'inbox.title': { en: 'Inbox', vi: 'Hộp thư' },
  'inbox.noMessages': { en: 'No messages yet', vi: 'Chưa có tin nhắn' },
  'inbox.clear': { en: 'Clear', vi: 'Xóa' },
  'inbox.typeMessage': { en: 'Type a message...', vi: 'Nhập tin nhắn...' },
  'inbox.send': { en: 'Send', vi: 'Gửi' },

  // Projects Page
  'projects.title': { en: 'Projects', vi: 'Dự án' },
  'projects.subtitle': { en: 'Explore featured projects', vi: 'Khám phá dự án nổi bật' },
  'projects.noFound': { en: 'No projects found', vi: 'Không tìm thấy dự án' },
  'projects.price': { en: 'Price from', vi: 'Giá từ' },
  'projects.viewDetails': { en: 'View Details', vi: 'Xem chi tiết' },

  // Info Page
  'info.contact': { en: 'Contact So Do Van Phuc', vi: 'Liên hệ So Do Van Phuc' },
  'info.sell.heading': { en: 'Sell your home', vi: 'Bán nhà của bạn' },
  'info.sell.description': { en: "Maximize your home's value with So Do Van Phuc's advanced selling tools, market insights, and a network of experienced agents ready to deliver results.", vi: 'Tối đa hóa giá trị căn nhà với công cụ bán hàng nâng cao, dữ liệu thị trường và mạng lưới môi giới giàu kinh nghiệm của So Do Van Phuc.' },
  'info.sell.marketTitle': { en: 'Market Analysis', vi: 'Phân tích thị trường' },
  'info.sell.marketDesc': { en: 'Get a comprehensive analysis of your local market to price your home competitively and attract qualified buyers.', vi: 'Nhận phân tích toàn diện về thị trường khu vực để định giá cạnh tranh và thu hút người mua phù hợp.' },
  'info.sell.listingTitle': { en: 'Professional Listing', vi: 'Tin đăng chuyên nghiệp' },
  'info.sell.listingDesc': { en: 'Your property will be showcased with professional photography, virtual tours, and premium placement on So Do Van Phuc.', vi: 'Bất động sản của bạn được giới thiệu bằng hình ảnh chuyên nghiệp, tour ảo và vị trí hiển thị nổi bật trên So Do Van Phuc.' },
  'info.sell.supportTitle': { en: 'Dedicated Support', vi: 'Hỗ trợ tận tâm' },
  'info.sell.supportDesc': { en: 'Work with experienced So Do Van Phuc agents who guide you through every step from listing to closing.', vi: 'Làm việc cùng các môi giới So Do Van Phuc giàu kinh nghiệm, được hỗ trợ từ lúc đăng tin đến khi hoàn tất giao dịch.' },
  'info.mortgage.heading': { en: 'So Do Van Phuc Home Loans', vi: 'Vay mua nhà So Do Van Phuc' },
  'info.mortgage.description': { en: 'Find the right mortgage for your dream home. Compare rates, get pre-approved, and close with confidence - all powered by So Do Van Phuc Home Loans.', vi: 'Tìm khoản vay mua nhà phù hợp cho căn nhà mơ ước. So sánh lãi suất, xin chấp thuận trước và hoàn tất giao dịch tự tin với So Do Van Phuc Home Loans.' },
  'info.mortgage.ratesTitle': { en: 'Competitive Rates', vi: 'Lãi suất cạnh tranh' },
  'info.mortgage.ratesDesc': { en: "Access today's most competitive mortgage rates with transparent terms and no hidden fees from So Do Van Phuc Home Loans.", vi: 'Tiếp cận các mức lãi vay mua nhà cạnh tranh với điều khoản minh bạch và không có phí ẩn từ So Do Van Phuc Home Loans.' },
  'info.mortgage.preApprovalTitle': { en: 'Pre-Approval', vi: 'Chấp thuận trước' },
  'info.mortgage.preApprovalDesc': { en: 'Get pre-approved in minutes with our streamlined digital application. Know your buying power before you start shopping.', vi: 'Xin chấp thuận trước chỉ trong vài phút với hồ sơ trực tuyến tinh gọn. Biết rõ khả năng mua trước khi bắt đầu tìm nhà.' },
  'info.mortgage.loanOptionsTitle': { en: 'Loan Options', vi: 'Lựa chọn khoản vay' },
  'info.mortgage.loanOptionsDesc': { en: 'Choose from conventional, FHA, VA, and jumbo loans tailored to your financial situation and homebuying goals.', vi: 'Chọn từ khoản vay thông thường, FHA, VA hoặc jumbo được thiết kế theo tình hình tài chính và mục tiêu mua nhà của bạn.' },
  'info.agent.heading': { en: 'Find a So Do Van Phuc Agent', vi: 'Tìm môi giới So Do Van Phuc' },
  'info.agent.description': { en: 'Connect with top-rated real estate professionals in your area. Our agents bring local expertise, market knowledge, and a commitment to your success.', vi: 'Kết nối với các chuyên viên bất động sản được đánh giá cao tại khu vực của bạn. Môi giới của chúng tôi có hiểu biết địa phương, dữ liệu thị trường và cam kết đồng hành đến kết quả tốt nhất.' },
  'info.agent.verifiedTitle': { en: 'Verified Professionals', vi: 'Chuyên viên đã xác minh' },
  'info.agent.verifiedDesc': { en: 'Every So Do Van Phuc agent is verified, licensed, and reviewed by past clients so you can choose with confidence.', vi: 'Mỗi môi giới So Do Van Phuc đều được xác minh, có giấy phép và có đánh giá từ khách hàng trước để bạn chọn lựa tự tin.' },
  'info.agent.localTitle': { en: 'Local Expertise', vi: 'Am hiểu địa phương' },
  'info.agent.localDesc': { en: 'Find agents who specialize in your target neighborhood and property type for the best market insights.', vi: 'Tìm môi giới chuyên về khu vực và loại bất động sản bạn quan tâm để có góc nhìn thị trường chính xác hơn.' },
  'info.agent.connectionTitle': { en: 'Seamless Connection', vi: 'Kết nối nhanh chóng' },
  'info.agent.connectionDesc': { en: 'Get matched with top-performing agents in your area and start a conversation within minutes.', vi: 'Được ghép với môi giới hiệu quả cao trong khu vực và bắt đầu trao đổi chỉ trong vài phút.' },

  // Home Footer
  'home.aboutRecommendations': { en: 'About So Do Van Phuc Recommendations', vi: 'Giới thiệu đề xuất So Do Van Phuc' },
  'home.downloadApp': { en: 'Download on the', vi: 'Tải xuống từ' },
  'home.appStore': { en: 'App Store', vi: 'App Store' },
  'home.getItOn': { en: 'GET IT ON', vi: 'TẢI TỪ' },
  'home.googlePlay': { en: 'Google Play', vi: 'Google Play' },

  // PropertyDetail extra (unique)
  'detail.stayConnected': { en: 'Stay connected', vi: 'Liên lạc' },
  'detail.openHouse': { en: 'Open house', vi: 'Mở cửa xem' },
  'detail.facts': { en: 'Facts & features', vi: 'Thông tin & đặc điểm' },
  'detail.offerInsights': { en: 'Offer insights', vi: 'Thông tin ưu đãi' },
  'detail.marketValue': { en: 'Market value', vi: 'Giá trị thị trường' },
  'detail.taxHistory': { en: 'Public tax history', vi: 'Lịch sử thuế' },
  'detail.priceHistory': { en: 'Price history', vi: 'Lịch sử giá' },
  'detail.monthlyPayment': { en: 'Monthly payment', vi: 'Thanh toán hàng tháng' },
  'detail.downPayment': { en: 'Down payment assistance', vi: 'Hỗ trợ trả trước' },
  'detail.climateRisks': { en: 'Climate risks', vi: 'Rủi ro khí hậu' },
  'detail.gettingAround': { en: 'Getting around', vi: 'Di chuyển' },
  'detail.nearbySchools': { en: 'Nearby schools', vi: 'Trường học lân cận' },
  'detail.localExperts': { en: 'Local experts', vi: 'Chuyên gia khu vực' },

  // Full i18n audit - shared labels and high-visibility sections
  'common.search': { en: 'Search', vi: 'Tìm kiếm' },
  'common.any': { en: 'Any', vi: 'Bất kỳ' },
  'common.selected': { en: 'selected', vi: 'đã chọn' },
  'common.for': { en: 'for', vi: 'cho' },
  'common.loadingInline': { en: 'Loading...', vi: 'Đang tải...' },
  'common.clear': { en: 'Clear', vi: 'Xóa' },
  'common.close': { en: 'Close', vi: 'Đóng' },
  'common.demoMode': { en: 'Preview mode:', vi: 'Chế độ xem trước:' },
  'prop.bedShort': { en: 'bd', vi: 'PN' },
  'prop.bedsLower': { en: 'beds', vi: 'PN' },
  'prop.bathsLower': { en: 'baths', vi: 'PT' },
  'prop.houseForSale': { en: 'House for Sale', vi: 'Nhà bán' },
  'prop.standard': { en: 'Standard', vi: 'Tiêu chuẩn' },
  'prop.perMonth': { en: '/mo', vi: '/tháng' },
  'prop.showcase': { en: 'Showcase', vi: 'Nổi bật' },
  'prop.warmFireplace': { en: 'Warm cozy fireplace', vi: 'Lò sưởi ấm cúng' },
  'prop.daysOnMarketShort': { en: '{count} days on market', vi: '{count} ngày trên thị trường' },
  'prop.openPrefix': { en: 'Open:', vi: 'Mở cửa:' },
  'recommend.title': { en: 'Get home recommendations', vi: 'Nhận gợi ý nhà phù hợp' },
  'recommend.subtitle': { en: 'Sign in for a more personalized experience.', vi: 'Đăng nhập để có trải nghiệm cá nhân hóa hơn.' },
  'recommend.titleLoggedIn': { en: 'Homes picked for you', vi: 'Nhà được chọn dành cho bạn' },
  'recommend.subtitleLoggedIn': { en: 'Based on your search activity and saved properties.', vi: 'Dựa trên hoạt động tìm kiếm và bất động sản đã lưu của bạn.' },
  'recommend.browseCta': { en: 'Browse properties', vi: 'Xem bất động sản' },
  'recommend.cardTitle': { en: 'Recommended homes', vi: 'Nhà được gợi ý' },
  'recommend.byBudget': { en: 'based on your monthly budget', vi: 'dựa trên ngân sách hàng tháng' },
  'recommend.byLocation': { en: 'based on your preferred location', vi: 'dựa trên khu vực bạn quan tâm' },
  'recommend.buyTitle': { en: 'Buy a home', vi: 'Mua nhà' },
  'recommend.buyDesc': { en: 'A real estate agent can provide you with a clear breakdown of costs so that you can avoid surprise expenses.', vi: 'Môi giới bất động sản có thể giúp bạn hiểu rõ từng khoản chi phí để tránh phát sinh bất ngờ.' },
  'recommend.buyCta': { en: 'Find a local agent', vi: 'Tìm môi giới' },
  'recommend.rentTitle': { en: 'Rent a home', vi: 'Thuê nhà' },
  'recommend.rentDesc': { en: "We're creating a seamless online experience - from shopping on the largest rental network, to applying, to paying rent.", vi: 'Chúng tôi tạo trải nghiệm trực tuyến liền mạch, từ tìm nhà thuê, nộp hồ sơ đến thanh toán tiền thuê.' },
  'recommend.rentCta': { en: 'Find rentals', vi: 'Tìm nhà cho thuê' },
  'recommend.sellTitle': { en: 'Sell a home', vi: 'Bán nhà' },
  'recommend.sellDesc': { en: 'No matter what path you take to sell your home, we can help you navigate a successful sale.', vi: 'Dù bạn chọn cách bán nhà nào, chúng tôi vẫn có thể hỗ trợ để giao dịch diễn ra hiệu quả.' },
  'recommend.sellCta': { en: 'See your options', vi: 'Xem lựa chọn' },
  'home.recommendationsDesc': { en: "Recommendations are based on your location and search activity, such as the homes you've viewed and saved and the filters you've used. We use this information to bring similar homes to your attention, so you don't miss out.", vi: 'Đề xuất dựa trên vị trí và hoạt động tìm kiếm của bạn, như các căn nhà đã xem, đã lưu và bộ lọc đã dùng. Chúng tôi dùng thông tin này để gợi ý những bất động sản tương tự để bạn không bỏ lỡ cơ hội phù hợp.' },
  'footer.realEstate': { en: 'Real Estate', vi: 'Bất động sản' },
  'footer.rentals': { en: 'Rentals', vi: 'Cho thuê' },
  'footer.mortgageRates': { en: 'Mortgage Rates', vi: 'Lãi suất vay' },
  'footer.homesForSale': { en: 'Homes for Sale', vi: 'Nhà bán' },
  'footer.foreclosures': { en: 'Foreclosures', vi: 'Nhà bị tịch thu' },
  'footer.newConstruction': { en: 'New Construction', vi: 'Nhà xây mới' },
  'footer.recentlySold': { en: 'Recently Sold', vi: 'Vừa bán' },
  'footer.allHomes': { en: 'All Homes', vi: 'Tất cả nhà' },
  'footer.apartmentsRent': { en: 'Apartments for Rent', vi: 'Căn hộ cho thuê' },
  'footer.housesRent': { en: 'Houses for Rent', vi: 'Nhà cho thuê' },
  'footer.allRentalListings': { en: 'All Rental Listings', vi: 'Tất cả tin cho thuê' },
  'footer.allRentalBuildings': { en: 'All Rental Buildings', vi: 'Tất cả tòa nhà cho thuê' },
  'footer.todaysRates': { en: "Today's Rates", vi: 'Lãi suất hôm nay' },
  'footer.refinanceRates': { en: 'Refinance Rates', vi: 'Lãi suất tái cấp vốn' },
  'footer.mortgageCalculator': { en: 'Mortgage Calculator', vi: 'Công cụ tính khoản vay' },
  'footer.affordabilityCalculator': { en: 'Affordability Calculator', vi: 'Công cụ tính khả năng mua' },
  'footer.allCities': { en: 'All Cities', vi: 'Tất cả thành phố' },
  'footer.fairHousing': { en: 'Fair Housing Guide', vi: 'Hướng dẫn nhà ở công bằng' },
  'footer.advocacy': { en: 'Advocacy', vi: 'Vận động chính sách' },
  'footer.adChoices': { en: 'Ad Choices', vi: 'Tùy chọn quảng cáo' },
  'footer.cookiePreference': { en: 'Cookie Preference', vi: 'Tùy chọn cookie' },
  'footer.mobileApps': { en: 'Mobile Apps', vi: 'Ứng dụng di động' },
  'footer.marketReports': { en: 'Market Reports', vi: 'Báo cáo thị trường' },
  'footer.doNotSell': { en: 'Do Not Sell or Share My Personal Information', vi: 'Không bán hoặc chia sẻ thông tin cá nhân của tôi' },
  'footer.accessibility': { en: 'sodovanphuc.vn is committed to ensuring digital accessibility for individuals with disabilities. We are continuously working to improve the accessibility of our web experience for everyone, and we welcome feedback and accommodation requests. If you wish to report an issue or seek an accommodation, please', vi: 'sodovanphuc.vn cam kết bảo đảm khả năng truy cập kỹ thuật số cho người khuyết tật. Chúng tôi liên tục cải thiện trải nghiệm truy cập cho mọi người và luôn hoan nghênh phản hồi cũng như yêu cầu hỗ trợ. Nếu bạn muốn báo cáo vấn đề hoặc cần hỗ trợ, vui lòng' },
  'footer.letUsKnow': { en: 'let us know', vi: 'liên hệ với chúng tôi' },
  'footer.affiliatedDisclosure': { en: 'Affiliated Business Arrangement Disclosure', vi: 'Công bố thỏa thuận kinh doanh liên kết' },
  'footer.licenses': { en: 'So Do Van Phuc Group holds real estate brokerage licenses in multiple jurisdictions. All mortgage lending products and information provided by So Do Van Phuc Home Loans, LLC.', vi: 'So Do Van Phuc Group có giấy phép môi giới bất động sản tại nhiều khu vực pháp lý. Tất cả sản phẩm vay mua nhà và thông tin liên quan được cung cấp bởi So Do Van Phuc Home Loans, LLC.' },
  'footer.equalHousing': { en: 'Equal Housing Lender', vi: 'Đơn vị cho vay nhà ở công bằng' },
  'footer.licensingInfo': { en: 'Licensing Information', vi: 'Thông tin giấy phép' },
  'footer.contactBrokerage': { en: 'Contact So Do Van Phuc Brokerage', vi: 'Liên hệ môi giới So Do Van Phuc' },
  'footer.followUs': { en: 'Follow us:', vi: 'Theo dõi chúng tôi:' },
  'footer.appStorePending': { en: 'App Store link will be added when the mobile app is available', vi: 'Liên kết App Store sẽ được thêm khi ứng dụng di động sẵn sàng' },
  'footer.googlePlayPending': { en: 'Google Play link will be added when the mobile app is available', vi: 'Liên kết Google Play sẽ được thêm khi ứng dụng di động sẵn sàng' },
  'listing.noMatches': { en: "We couldn't find any properties matching your criteria. Try adjusting your filters or browse all available listings.", vi: 'Chúng tôi không tìm thấy bất động sản phù hợp với tiêu chí của bạn. Hãy thử điều chỉnh bộ lọc hoặc xem tất cả tin đăng hiện có.' },
  'listing.compareSelected': { en: '{count}/3 selected', vi: 'Đã chọn {count}/3' },
  'filter.areaSqft': { en: 'Area (sqft)', vi: 'Diện tích (m²)' },
  'filter.min': { en: 'Min', vi: 'Tối thiểu' },
  'filter.max': { en: 'Max', vi: 'Tối đa' },
  'filter.any': { en: 'Any', vi: 'Bất kỳ' },
  'filter.forSale': { en: 'For Sale', vi: 'Bán' },
  'filter.forRent': { en: 'For Rent', vi: 'Cho thuê' },
  'filter.anyPriceSale': { en: 'Any Price', vi: 'Mọi giá' },
  'filter.under500k': { en: 'Under $500K', vi: 'Dưới $500K' },
  'filter.500k1m': { en: '$500K - $1M', vi: '$500K - $1M' },
  'filter.1m2m': { en: '$1M - $2M', vi: '$1M - $2M' },
  'filter.2mPlus': { en: '$2M+', vi: 'Trên $2M' },
  'filter.under2500': { en: 'Under $2,500/mo', vi: 'Dưới $2,500/tháng' },
  'filter.25004000': { en: '$2,500 - $4,000/mo', vi: '$2,500 - $4,000/tháng' },
  'filter.40006000': { en: '$4,000 - $6,000/mo', vi: '$4,000 - $6,000/tháng' },
  'filter.6000Plus': { en: '$6,000+/mo', vi: 'Trên $6,000/tháng' },
  'type.singleFamily': { en: 'Single Family', vi: 'Nhà riêng' },
  'type.condo': { en: 'Condo', vi: 'Căn hộ' },
  'type.townhouse': { en: 'Townhouse', vi: 'Nhà phố' },
  'share.title': { en: 'Share this listing', vi: 'Chia sẻ tin đăng' },
  'share.copied': { en: 'Copied!', vi: 'Đã sao chép!' },
  'share.copiedOpening': { en: 'Copied, opening {platform}', vi: 'Đã sao chép, đang mở {platform}' },
  'share.copyLink': { en: 'Copy link', vi: 'Sao chép liên kết' },
  'paypal.notConfigured': { en: 'PayPal is not configured. Free listings can post now.', vi: 'PayPal chưa được cấu hình. Tin miễn phí vẫn có thể đăng ngay.' },
  'paypal.loading': { en: 'Loading PayPal...', vi: 'Đang tải PayPal...' },
  'paypal.selectPro': { en: 'Select Pro plan to enable payment', vi: 'Chọn gói Pro để bật thanh toán' },
  'paypal.clientMissing': { en: 'PayPal Client ID not configured', vi: 'Chưa cấu hình PayPal Client ID' },
  'paypal.loadFailed': { en: 'Failed to load PayPal SDK', vi: 'Không thể tải PayPal SDK' },
  'phone.searchCountry': { en: 'Search country...', vi: 'Tìm quốc gia...' },
  'phone.noCountries': { en: 'No countries found', vi: 'Không tìm thấy quốc gia' },
  'phone.country.us': { en: 'United States', vi: 'Hoa Kỳ' },
  'phone.country.vn': { en: 'Vietnam', vi: 'Việt Nam' },
  'phone.country.uk': { en: 'United Kingdom', vi: 'Vương quốc Anh' },
  'phone.country.au': { en: 'Australia', vi: 'Úc' },
  'phone.country.ca': { en: 'Canada', vi: 'Canada' },
  'phone.country.fr': { en: 'France', vi: 'Pháp' },
  'phone.country.de': { en: 'Germany', vi: 'Đức' },
  'phone.country.jp': { en: 'Japan', vi: 'Nhật Bản' },
  'phone.country.kr': { en: 'South Korea', vi: 'Hàn Quốc' },
  'phone.country.cn': { en: 'China', vi: 'Trung Quốc' },
  'phone.country.th': { en: 'Thailand', vi: 'Thái Lan' },
  'phone.country.sg': { en: 'Singapore', vi: 'Singapore' },
  'phone.country.my': { en: 'Malaysia', vi: 'Malaysia' },
  'phone.country.ph': { en: 'Philippines', vi: 'Philippines' },
  'phone.country.in': { en: 'India', vi: 'Ấn Độ' },
  'phone.country.id': { en: 'Indonesia', vi: 'Indonesia' },
  'phone.country.tw': { en: 'Taiwan', vi: 'Đài Loan' },
  'phone.country.hk': { en: 'Hong Kong', vi: 'Hồng Kông' },
  'phone.country.ae': { en: 'UAE', vi: 'UAE' },
  'phone.country.ru': { en: 'Russia', vi: 'Nga' },
  'phone.country.br': { en: 'Brazil', vi: 'Brazil' },
  'phone.country.mx': { en: 'Mexico', vi: 'Mexico' },
  'phone.country.it': { en: 'Italy', vi: 'Ý' },
  'phone.country.es': { en: 'Spain', vi: 'Tây Ban Nha' },
  'phone.country.nl': { en: 'Netherlands', vi: 'Hà Lan' },
  'phone.country.se': { en: 'Sweden', vi: 'Thụy Điển' },
  'phone.country.ch': { en: 'Switzerland', vi: 'Thụy Sĩ' },
  'phone.country.nz': { en: 'New Zealand', vi: 'New Zealand' },
  'auth.emailUsernameRequired': { en: 'Email or username is required.', vi: 'Vui lòng nhập email hoặc tên đăng nhập.' },
  'auth.emailRequired': { en: 'Email is required.', vi: 'Vui lòng nhập email.' },
  'auth.passwordRequired': { en: 'Password is required.', vi: 'Vui lòng nhập mật khẩu.' },
  'auth.newPasswordRequired': { en: 'New password is required.', vi: 'Vui lòng nhập mật khẩu mới.' },
  'auth.passwordMin': { en: 'Password must be at least 6 characters.', vi: 'Mật khẩu phải có ít nhất 6 ký tự.' },
  'auth.confirmPasswordRequired': { en: 'Please confirm your password.', vi: 'Vui lòng xác nhận mật khẩu.' },
  'auth.confirmNewPasswordRequired': { en: 'Please confirm your new password.', vi: 'Vui lòng xác nhận mật khẩu mới.' },
  'auth.passwordsNoMatch': { en: 'Passwords do not match.', vi: 'Mật khẩu không khớp.' },
  'auth.invalidCredentials': { en: 'Invalid credentials', vi: 'Thông tin đăng nhập không hợp lệ' },
  'auth.invalidEmailPassword': { en: 'Invalid email or password', vi: 'Email hoặc mật khẩu không đúng' },
  'auth.connectFailed': { en: 'Unable to connect to server. Please try again later.', vi: 'Không thể kết nối máy chủ. Vui lòng thử lại sau.' },
  'auth.connectionFailed': { en: 'Connection failed. Please try again.', vi: 'Kết nối thất bại. Vui lòng thử lại.' },
  'auth.registrationFailed': { en: 'Registration failed. Please try again.', vi: 'Đăng ký thất bại. Vui lòng thử lại.' },
  'auth.resetInstructionsSent': { en: 'Reset Instructions Sent', vi: 'Đã gửi hướng dẫn đặt lại' },
  'auth.resetInstructionsDesc': { en: 'Password reset instructions have been sent to {email}.', vi: 'Hướng dẫn đặt lại mật khẩu đã được gửi đến {email}.' },
  'auth.resetCheckInbox': { en: 'Check your inbox (and spam folder) for the reset link. The link will expire in 1 hour.', vi: 'Hãy kiểm tra hộp thư đến và thư rác để lấy liên kết đặt lại. Liên kết sẽ hết hạn sau 1 giờ.' },
  'auth.resetDemo': { en: 'No real email is sent. Use the link below to reset your password.', vi: 'Không có email thật nào được gửi. Hãy dùng liên kết bên dưới để đặt lại mật khẩu.' },
  'auth.resetNow': { en: 'Reset Password Now', vi: 'Đặt lại mật khẩu ngay' },
  'auth.passwordUpdated': { en: 'Password Updated Successfully', vi: 'Cập nhật mật khẩu thành công' },
  'auth.passwordUpdatedDesc': { en: 'Your password has been changed. You can now sign in with your new password.', vi: 'Mật khẩu của bạn đã được thay đổi. Bây giờ bạn có thể đăng nhập bằng mật khẩu mới.' },
  'auth.signInNewPassword': { en: 'Sign in with new password', vi: 'Đăng nhập bằng mật khẩu mới' },
  'auth.invalidResetLink': { en: 'Invalid reset link. Please use the link from your email.', vi: 'Liên kết đặt lại không hợp lệ. Vui lòng dùng liên kết trong email của bạn.' },
  'auth.resetFailed': { en: 'Failed to reset password. The link may have expired.', vi: 'Không thể đặt lại mật khẩu. Liên kết có thể đã hết hạn.' },
  'auth.networkTryAgain': { en: 'Network error. Please try again.', vi: 'Lỗi mạng. Vui lòng thử lại.' },
  'auth.passwordChanged': { en: 'Password Changed!', vi: 'Đã đổi mật khẩu!' },
  'auth.passwordChangedDesc': { en: 'Your password has been updated.', vi: 'Mật khẩu của bạn đã được cập nhật.' },
  'auth.changePasswordFailed': { en: 'Failed to change password', vi: 'Không thể đổi mật khẩu' },
  'auth.currentPasswordRequired': { en: 'Current password is required.', vi: 'Vui lòng nhập mật khẩu hiện tại.' },
  'header.switchLanguage': { en: 'Switch language', vi: 'Đổi ngôn ngữ' },
  'auth.fullNameRequired': { en: 'Full name is required.', vi: 'Vui lòng nhập họ và tên.' },
  'auth.emailUsernamePlaceholder': { en: 'Email or account name', vi: 'Email hoặc tài khoản quản trị' },
  'auth.passwordPlaceholder': { en: 'Enter password', vi: 'Nhập mật khẩu' },
  'auth.signingIn': { en: 'Signing in...', vi: 'Đang đăng nhập...' },
  'auth.resetDemoPassword': { en: 'This is a simulated password reset. No actual password is changed.', vi: 'Đây là thao tác đặt lại mật khẩu mô phỏng. Không có mật khẩu thật nào được thay đổi.' },
  'admin.login.title': { en: 'Admin Login', vi: 'Đăng nhập quản trị' },
  'admin.login.subtitle': { en: 'Sign in to access the admin dashboard', vi: 'Đăng nhập để truy cập bảng quản trị' },
  'admin.login.username': { en: 'Username', vi: 'Tên đăng nhập' },
  'admin.login.required': { en: 'Username and password are required', vi: 'Vui lòng nhập tên đăng nhập và mật khẩu' },
  'contact.heroDesc': { en: 'Have questions about U.S. real estate? Reach out - our team is ready to help you find the perfect property.', vi: 'Bạn có câu hỏi về bất động sản tại Mỹ? Hãy liên hệ, đội ngũ của chúng tôi sẵn sàng giúp bạn tìm bất động sản phù hợp.' },
  'contact.callNow': { en: 'Call Now', vi: 'Gọi ngay' },
  'contact.emailUs': { en: 'Email Us', vi: 'Gửi email' },
  'contact.inquirySubmitted': { en: 'Inquiry Submitted', vi: 'Đã gửi yêu cầu' },
  'contact.inquirySubmittedDesc': { en: 'Your inquiry has been submitted. Our team will respond within 24 hours. You can also reach us directly via phone or email above.', vi: 'Yêu cầu của bạn đã được gửi. Đội ngũ của chúng tôi sẽ phản hồi trong vòng 24 giờ. Bạn cũng có thể liên hệ trực tiếp qua điện thoại hoặc email bên trên.' },
  'contact.sendAnother': { en: 'Send another message', vi: 'Gửi tin nhắn khác' },
  'contact.namePlaceholder': { en: 'Your full name', vi: 'Họ và tên của bạn' },
  'contact.phoneOptional': { en: 'Phone (optional)', vi: 'Số điện thoại (không bắt buộc)' },
  'contact.phonePlaceholder': { en: 'Your phone number', vi: 'Số điện thoại của bạn' },
  'contact.messagePlaceholder': { en: 'Tell us about your inquiry - property interest, budget, timeline...', vi: 'Cho chúng tôi biết nhu cầu của bạn - bất động sản quan tâm, ngân sách, thời gian...' },
  'contact.aiSuggest': { en: '✨ AI Suggest', vi: '✨ AI Gợi ý' },
  'contact.submitInquiry': { en: 'Submit Inquiry', vi: 'Gửi yêu cầu' },
  'contact.businessHours': { en: 'Business Hours:', vi: 'Giờ làm việc:' },
  'contact.businessHoursDesc': { en: 'Monday - Saturday, 8:00 AM - 6:00 PM (ICT, UTC+7). We typically respond to all inquiries within 24 hours during business days.', vi: 'Thứ Hai - Thứ Bảy, 8:00 - 18:00 (ICT, UTC+7). Chúng tôi thường phản hồi mọi yêu cầu trong vòng 24 giờ vào ngày làm việc.' },
  'contact.sendFailed': { en: 'Failed to send message. Please try again.', vi: 'Không thể gửi tin nhắn. Vui lòng thử lại.' },
  'blog.subtitleFull': { en: 'Expert analysis, buying guides, and investment strategies to help you make smarter real estate decisions.', vi: 'Phân tích chuyên sâu, hướng dẫn mua nhà và chiến lược đầu tư giúp bạn đưa ra quyết định bất động sản thông minh hơn.' },
  'blog.notFoundDesc': { en: "The blog post you're looking for doesn't exist or has been removed.", vi: 'Bài viết bạn đang tìm không tồn tại hoặc đã bị gỡ bỏ.' },
  'blog.relatedPosts': { en: 'Related Posts', vi: 'Bài viết liên quan' },
  'scroll.backToTop': { en: 'Back to top', vi: 'Lên đầu trang' },
  'compare.backToListings': { en: 'Back to listings', vi: 'Quay lại danh sách' },
  'compare.selectedCount': { en: '{count} of 3 properties selected', vi: 'Đã chọn {count}/3 bất động sản' },
  'compare.none': { en: 'None', vi: 'Không có' },
  'compare.field.status': { en: 'Status', vi: 'Trạng thái' },
  'compare.field.type': { en: 'Type', vi: 'Loại' },
  'compare.field.city': { en: 'City', vi: 'Thành phố' },
  'compare.field.state': { en: 'State', vi: 'Bang/Tỉnh' },
  'compare.field.address': { en: 'Address', vi: 'Địa chỉ' },
  'compare.field.yearBuilt': { en: 'Year Built', vi: 'Năm xây dựng' },
  'compare.field.lotSize': { en: 'Lot Size', vi: 'Diện tích đất' },
  'compare.field.priceSqft': { en: 'Price/sqft', vi: 'Giá/m²' },
  'compare.field.hoaFee': { en: 'HOA Fee', vi: 'Phí HOA' },
  'projects.subtitleFull': { en: 'Explore premium real estate developments across the United States.', vi: 'Khám phá các dự án bất động sản cao cấp trên khắp Hoa Kỳ.' },
  'projects.searchPlaceholder': { en: 'Search projects by name, location, or developer...', vi: 'Tìm dự án theo tên, vị trí hoặc chủ đầu tư...' },
  'projects.projectSingular': { en: 'project', vi: 'dự án' },
  'projects.projectPlural': { en: 'projects', vi: 'dự án' },
  'projects.matching': { en: 'matching', vi: 'khớp với' },
  'projects.allProjects': { en: 'All Projects', vi: 'Tất cả dự án' },
  'projects.preSale': { en: 'Pre-Sale', vi: 'Mở bán sớm' },
  'projects.underConstruction': { en: 'Under Construction', vi: 'Đang xây dựng' },
  'projects.completed': { en: 'Completed', vi: 'Đã hoàn thành' },
  'projects.soldOut': { en: 'Sold Out', vi: 'Đã bán hết' },
  'projects.units': { en: 'units', vi: 'căn' },
  'projects.priceRange': { en: 'Price Range', vi: 'Khoảng giá' },
  'projects.noMatches': { en: "We couldn't find any projects matching your criteria. Try adjusting your search or filter.", vi: 'Chúng tôi không tìm thấy dự án nào phù hợp với tiêu chí của bạn. Hãy thử điều chỉnh tìm kiếm hoặc bộ lọc.' },
  'inbox.onlineExpert': { en: 'Online - U.S. Real Estate Expert', vi: 'Đang online - Chuyên gia bất động sản Hoa Kỳ' },
  'inbox.talkAgent': { en: 'Talk to a real agent via WhatsApp', vi: 'Trao đổi với tư vấn viên qua WhatsApp' },
  'inbox.clearHistory': { en: 'Clear chat history', vi: 'Xóa lịch sử trò chuyện' },
  'inbox.aiThinking': { en: 'AI is thinking...', vi: 'AI đang suy nghĩ...' },
  'inbox.askPlaceholder': { en: 'Ask about U.S. real estate...', vi: 'Hỏi về bất động sản Hoa Kỳ...' },
  'inbox.notConfigured': { en: 'AI Assistant is not configured on the server yet. Please set the backend AI key before enabling this feature.', vi: 'Tro ly AI chua duoc cau hinh tren may chu. Hay cau hinh AI key o backend truoc khi bat tinh nang nay.' },
  'inbox.connectionIssue': { en: "Sorry, I'm having connection issues. Please try again in a moment.", vi: 'Xin lỗi, tôi đang gặp sự cố kết nối. Vui lòng thử lại sau ít phút.' },
  'inbox.error': { en: 'Sorry, an error occurred. Please try again.', vi: 'Xin lỗi, đã xảy ra lỗi. Vui lòng thử lại.' },
  'inbox.suggestionTrends': { en: 'What are current U.S. market trends?', vi: 'Xu hướng thị trường Hoa Kỳ hiện nay là gì?' },
  'inbox.suggestionCities': { en: 'Best cities to invest in right now?', vi: 'Thành phố nào đáng đầu tư hiện nay?' },
  'inbox.suggestionMortgage': { en: 'How do I get a mortgage?', vi: 'Làm sao để vay mua nhà?' },
  'inbox.suggestionList': { en: 'How to list my property?', vi: 'Làm sao để đăng bất động sản?' },
  'inbox.welcome': { en: "Hi there! I'm the So Do Van Phuc AI Assistant.\n\nI can help you with:\n- U.S. real estate market insights & trends\n- Neighborhood recommendations & pricing\n- Mortgage & home buying guidance\n- Listing your property on So Do Van Phuc\n\nFeel free to ask me anything!", vi: 'Xin chào! Tôi là So Do Van Phuc AI Assistant.\n\nTôi có thể hỗ trợ bạn về:\n- Góc nhìn và xu hướng thị trường bất động sản Hoa Kỳ\n- Gợi ý khu vực và tham khảo giá\n- Hướng dẫn vay mua nhà và mua bất động sản\n- Đăng bất động sản trên So Do Van Phuc\n\nBạn cứ đặt câu hỏi nhé!' },
  'inbox.agent': { en: 'Agent', vi: 'Tư vấn viên' },
  'inbox.assistantName': { en: 'AI Assistant', vi: 'Trợ lý AI' },
  'post.draftSaved': { en: 'Draft auto-saved', vi: 'Bản nháp đã tự động lưu' },
  'post.successPublishedTitle': { en: 'Listing Published Successfully!', vi: 'Tin đăng đã được xuất bản!' },
  'post.successPublishedMsg': { en: 'Your listing is now live and visible to all users.', vi: 'Tin đăng của bạn hiện đã hiển thị với tất cả người dùng.' },
  'post.max10': { en: '$0 - Max 10', vi: '$0 - Tối đa 10' },
  'post.proFrom': { en: 'From $9 - Priority display', vi: 'Từ $9 - Ưu tiên hiển thị' },
  'post.proVip': { en: 'Pro - VIP', vi: 'Pro - VIP' },
  'post.order': { en: 'Order:', vi: 'Mã đơn:' },
  'post.total': { en: 'Total:', vi: 'Tổng cộng:' },
  'post.proListingDays': { en: 'Pro listing - {days} days', vi: 'Tin Pro - {days} ngày' },
  'post.fullNameRequired': { en: 'Full name is required', vi: 'Vui lòng nhập họ tên' },
  'post.phoneRequired': { en: 'Phone number is required', vi: 'Vui lòng nhập số điện thoại' },
  'post.emailRequired': { en: 'Email is required', vi: 'Vui lòng nhập email' },
  'post.noDescription': { en: 'No description provided.', vi: 'Chưa có mô tả.' },
  'post.linkMustStart': { en: '{label} link must start with http:// or https://', vi: 'Liên kết {label} phải bắt đầu bằng http:// hoặc https://' },
  'post.whatsappInvalid': { en: 'WhatsApp must be a phone number or a link starting with http:// or https://', vi: 'WhatsApp phải là số điện thoại hoặc liên kết bắt đầu bằng http:// hoặc https://' },
  'post.generating': { en: 'Generating...', vi: 'Đang tạo...' },
  'post.aiGenerate': { en: 'AI Generate', vi: 'Tạo bằng AI' },
  'post.descriptionPlaceholder': { en: 'Describe your property - highlight key features, recent updates, and neighborhood benefits...', vi: 'Mô tả bất động sản - nêu bật đặc điểm chính, cập nhật gần đây và lợi ích khu vực...' },
  'post.contactVisibility': { en: 'These contacts belong to this listing only. Buyers will use them to call, email, or message the owner/agent for this property.', vi: 'Các thông tin này chỉ áp dụng cho riêng tin đăng này. Khách sẽ dùng để gọi, email hoặc nhắn chủ nhà/môi giới phụ trách tin này.' },
  'post.videoTooLarge': { en: 'Video must be {size}MB or smaller', vi: 'Video phải có dung lượng {size}MB trở xuống' },
  'post.submitErrorSupport': { en: 'Submission failed. Please try again or contact support.', vi: 'Gửi tin thất bại. Vui lòng thử lại hoặc liên hệ hỗ trợ.' },
  'post.submitErrorRetry': { en: 'Submission failed. Please try again.', vi: 'Gửi tin thất bại. Vui lòng thử lại.' },
  'post.selectPhotos': { en: 'Tap to select photos', vi: 'Nhấn để chọn ảnh' },
  'post.dragDropPhotos': { en: 'or drag and drop - up to {max} images, max {size}MB each', vi: 'hoặc kéo thả - tối đa {max} ảnh, mỗi ảnh tối đa {size}MB' },
  'post.photosSelected': { en: '{count}/{max} photos selected', vi: 'Đã chọn {count}/{max} ảnh' },
  'post.processing': { en: 'Processing...', vi: 'Đang xử lý...' },
  'post.removeAll': { en: 'Remove all', vi: 'Xóa tất cả' },
  'post.cover': { en: 'Cover', vi: 'Ảnh bìa' },
  'post.apiMode': { en: 'Media upload:', vi: 'Tải ảnh:' },
  'post.apiModeDesc': { en: 'Photos and videos will be processed, watermarked, and attached to this listing.', vi: 'Ảnh và video sẽ được xử lý, đóng watermark và gắn vào hồ sơ nhà này.' },
  'post.demoModeDesc': { en: 'Photos and videos will be prepared and attached to this listing.', vi: 'Ảnh và video sẽ được chuẩn bị và gắn vào hồ sơ nhà này.' },
  'post.selectVideo': { en: 'Select up to {max} video from your device', vi: 'Chọn tối đa {max} video từ thiết bị' },
  'post.videoFormats': { en: 'MP4, MOV or WebM - max {size}MB', vi: 'MP4, MOV hoặc WebM - tối đa {size}MB' },
  'post.mbSelected': { en: '{size}MB selected', vi: 'Đã chọn {size}MB' },
  'post.importLinksDesc': { en: 'Paste YouTube or social media links for this listing. YouTube links will show as an embedded video tour.', vi: 'Dán liên kết YouTube hoặc mạng xã hội cho tin đăng này. Liên kết YouTube sẽ hiển thị thành video tham quan nhúng.' },
  'post.contactNameHelp': { en: 'Shown as the owner or agent responsible for this listing.', vi: 'Hiển thị là chủ nhà hoặc môi giới phụ trách riêng tin này.' },
  'post.contactPhoneHelp': { en: 'Buyers can call this number directly from the listing.', vi: 'Khách có thể gọi trực tiếp số này từ trang tin đăng.' },
  'post.contactWhatsappHelp': { en: 'Leave blank to use the call phone number for WhatsApp.', vi: 'Bỏ trống thì hệ thống dùng số điện thoại gọi làm WhatsApp.' },
  'post.contactEmailHelp': { en: "Used as this listing's email contact for buyer inquiries.", vi: 'Dùng làm email liên hệ riêng của tin đăng khi khách gửi yêu cầu.' },
  'detail.propertyDetails': { en: 'Property Details', vi: 'Chi tiết bất động sản' },
  'detail.propertyNotFound': { en: 'Property not found', vi: 'Không tìm thấy bất động sản' },
  'detail.propertyNotFoundDesc': { en: "The property you're looking for doesn't exist or may have been removed.", vi: 'Bất động sản bạn đang tìm không tồn tại hoặc có thể đã bị gỡ.' },
  'detail.agentFallback': { en: 'Listing Agent', vi: 'Môi giới đăng tin' },
  'detail.licensedProfessional': { en: 'Licensed Real Estate Professional', vi: 'Chuyên viên bất động sản được cấp phép' },
  'detail.sendInquiry': { en: 'Send an inquiry', vi: 'Gửi yêu cầu tư vấn' },
  'detail.chatWhatsapp': { en: 'Chat via WhatsApp', vi: 'Nhắn qua WhatsApp' },
  'detail.whatsappUnavailable': { en: 'WhatsApp unavailable', vi: 'WhatsApp không khả dụng' },
  'detail.callAgent': { en: 'Call agent', vi: 'Gọi môi giới' },
  'detail.messageAgent': { en: 'Message agent', vi: 'Nhắn môi giới' },
  'detail.browseListings': { en: 'Browse Listings', vi: 'Xem tin đăng' },
  'detail.inquiryPlaceholder': { en: "I'm interested in {address}...", vi: 'Tôi quan tâm đến {address}...' },
  'detail.photoAlt': { en: 'Photo {count}', vi: 'Ảnh {count}' },
  'detail.shareText': { en: 'View this property on So Do Van Phuc', vi: 'Xem bất động sản này trên So Do Van Phuc' },
  'detail.sharePrompt': { en: 'Copy this link to share:', vi: 'Sao chép liên kết này để chia sẻ:' },
  'detail.unknown': { en: 'Unknown', vi: 'Không xác định' },
  'detail.inquiryFailed': { en: 'Failed to send inquiry. Please try again.', vi: 'Không thể gửi yêu cầu. Vui lòng thử lại.' },
  'detail.scheduleFailed': { en: 'Failed to schedule viewing. Please try again.', vi: 'Không thể đặt lịch xem. Vui lòng thử lại.' },
  'detail.seeAllPhotos': { en: 'See all {count} photos', vi: 'Xem tất cả {count} ảnh' },
  'detail.floorPlan': { en: 'Floor Plan', vi: 'Mặt bằng' },
  'detail.threeDHome': { en: '3D Home', vi: 'Nhà 3D' },
  'detail.photosCount': { en: '{count} Photos', vi: '{count} ảnh' },
  'detail.videoTour': { en: 'Video Tour', vi: 'Video tham quan' },
  'detail.compareFull': { en: 'Compare list is full (max 3)', vi: 'Danh sách so sánh đã đầy (tối đa 3)' },
  'detail.removeCompare': { en: 'Remove from compare', vi: 'Bỏ khỏi so sánh' },
  'detail.addCompare': { en: 'Add to compare', vi: 'Thêm vào so sánh' },
  'detail.inCompare': { en: 'In Compare', vi: 'Đang so sánh' },
  'detail.listingLinks': { en: 'Listing links', vi: 'Liên kết tin đăng' },
  'detail.type': { en: 'Type', vi: 'Loại' },
  'detail.built': { en: 'Built', vi: 'Năm xây' },
  'detail.lot': { en: 'Lot', vi: 'Đất' },
  'detail.pricePerSqft': { en: '$/sqft', vi: 'Giá/m²' },
  'detail.taxPerYear': { en: 'Tax/yr', vi: 'Thuế/năm' },
  'detail.none': { en: 'None', vi: 'Không có' },
  'detail.hide': { en: 'Hide', vi: 'Ẩn' },
  'detail.showMore': { en: 'Show more', vi: 'Xem thêm' },
  'detail.daysOnSo Do Van Phuc': { en: 'days on So Do Van Phuc', vi: 'ngày trên So Do Van Phuc' },
  'detail.views': { en: 'views', vi: 'lượt xem' },
  'detail.saves': { en: 'saves', vi: 'lượt lưu' },
  'detail.listedBy': { en: 'Listed by:', vi: 'Đăng bởi:' },
  'detail.mapAfterLaunch': { en: 'Interactive map available after launch', vi: 'Bản đồ tương tác sẽ có sau khi ra mắt' },
  'detail.travelTimes': { en: 'Travel times', vi: 'Thời gian di chuyển' },
  'detail.addToCalendar': { en: 'Add to calendar', vi: 'Thêm vào lịch' },
  'detail.interior': { en: 'Interior', vi: 'Nội thất' },
  'detail.construction': { en: 'Construction', vi: 'Xây dựng' },
  'detail.utilities': { en: 'Utilities', vi: 'Tiện ích' },
  'detail.communityHoa': { en: 'Community & HOA', vi: 'Cộng đồng & HOA' },
  'detail.financialDetails': { en: 'Financial & listing details', vi: 'Tài chính & chi tiết tin đăng' },
  'detail.contactQuestion': { en: 'Have a question about this property? Fill out the form below.', vi: 'Bạn có câu hỏi về bất động sản này? Hãy điền biểu mẫu bên dưới.' },
  'detail.offerStrong': { en: 'Strong', vi: 'Mạnh' },
  'detail.offerCompetitive': { en: 'Competitive', vi: 'Cạnh tranh' },
  'detail.offerModerate': { en: 'Moderate', vi: 'Trung bình' },
  'detail.offerWeak': { en: 'Weak', vi: 'Yếu' },
  'detail.offerRange': { en: 'Estimated offer range:', vi: 'Khoảng đề nghị ước tính:' },
  'detail.winChance': { en: '{chance} chance of a winning offer', vi: '{chance} cơ hội đề nghị được chấp nhận' },
  'detail.buyerProfile': { en: 'Buyer profile', vi: 'Hồ sơ người mua' },
  'detail.buyerProfileHint': { en: 'Set up your profile to see personalized insights', vi: 'Thiết lập hồ sơ để xem thông tin cá nhân hóa' },
  'detail.estimatedSalesRange': { en: 'Estimated sales range', vi: 'Khoảng giá bán ước tính' },
  'detail.estimatedMarketValue': { en: 'Estimated market value', vi: 'Giá trị thị trường ước tính' },
  'detail.estimatedMonthlyRent': { en: 'Estimated monthly rent', vi: 'Giá thuê hằng tháng ước tính' },
  'detail.marketUnavailable': { en: 'Market value data is not available for this property', vi: 'Chưa có dữ liệu giá trị thị trường cho bất động sản này' },
  'detail.viewTaxRecords': { en: 'View tax records ({count} years)', vi: 'Xem hồ sơ thuế ({count} năm)' },
  'detail.year': { en: 'Year', vi: 'Năm' },
  'detail.tax': { en: 'Tax', vi: 'Thuế' },
  'detail.assessment': { en: 'Assessment', vi: 'Định giá' },
  'detail.taxUnavailable': { en: 'Tax history is unavailable for this property', vi: 'Chưa có lịch sử thuế cho bất động sản này' },
  'detail.date': { en: 'Date', vi: 'Ngày' },
  'detail.event': { en: 'Event', vi: 'Sự kiện' },
  'detail.price': { en: 'Price', vi: 'Giá' },
  'detail.paymentEstimate': { en: 'Estimated monthly payment - 30-yr fixed - 6.85% - 20% down', vi: 'Ước tính thanh toán hằng tháng - cố định 30 năm - 6,85% - trả trước 20%' },
  'detail.principalInterest': { en: 'Principal & interest', vi: 'Gốc & lãi' },
  'detail.loanDetail': { en: 'Based on a {amount} loan amount at 6.85% interest rate over 30 years', vi: 'Dựa trên khoản vay {amount} với lãi suất 6,85% trong 30 năm' },
  'detail.propertyTax': { en: 'Property tax', vi: 'Thuế bất động sản' },
  'detail.taxDetail': { en: 'Estimated annual tax: ${amount} - Tax rate: ~{rate}%', vi: 'Thuế hằng năm ước tính: ${amount} - Thuế suất: ~{rate}%' },
  'detail.homeInsurance': { en: 'Home insurance', vi: 'Bảo hiểm nhà' },
  'detail.insuranceDetail': { en: 'Estimated annual home insurance based on 0.4% of home value', vi: 'Bảo hiểm nhà hằng năm ước tính dựa trên 0,4% giá trị nhà' },
  'detail.hoaDetail': { en: 'Monthly HOA dues paid to the homeowners association', vi: 'Phí HOA hằng tháng trả cho hiệp hội cư dân' },
  'detail.programsAvailable': { en: 'Programs available in your area', vi: 'Có chương trình hỗ trợ trong khu vực của bạn' },
  'detail.downPaymentQualify': { en: 'You may qualify for down payment assistance programs', vi: 'Bạn có thể đủ điều kiện nhận hỗ trợ trả trước' },
  'detail.checkEligibility': { en: 'Check eligibility', vi: 'Kiểm tra điều kiện' },
  'detail.environmentalRiskDesc': { en: 'Environmental risk data for informational purposes. Estimates may vary.', vi: 'Dữ liệu rủi ro môi trường chỉ để tham khảo. Ước tính có thể thay đổi.' },
  'detail.riskMinimal': { en: 'Minimal', vi: 'Rất thấp' },
  'detail.riskMinor': { en: 'Minor', vi: 'Thấp' },
  'detail.riskModerate': { en: 'Moderate', vi: 'Trung bình' },
  'detail.riskMajor': { en: 'Major', vi: 'Cao' },
  'detail.riskSevere': { en: 'Severe', vi: 'Rất cao' },
  'detail.flood': { en: 'Flood', vi: 'Ngập lụt' },
  'detail.fire': { en: 'Fire', vi: 'Cháy' },
  'detail.heat': { en: 'Heat', vi: 'Nắng nóng' },
  'detail.wind': { en: 'Wind', vi: 'Gió' },
  'detail.walkScore': { en: 'Walk Score', vi: 'Đi bộ' },
  'detail.bikeScore': { en: 'Bike Score', vi: 'Đạp xe' },
  'detail.transitScore': { en: 'Transit Score', vi: 'Giao thông công cộng' },
  'detail.walkParadise': { en: "Walker's Paradise", vi: 'Rất thuận tiện đi bộ' },
  'detail.veryWalkable': { en: 'Very Walkable', vi: 'Dễ đi bộ' },
  'detail.somewhatWalkable': { en: 'Somewhat Walkable', vi: 'Có thể đi bộ' },
  'detail.carDependent': { en: 'Car-Dependent', vi: 'Phụ thuộc vào xe' },
  'detail.carRequired': { en: 'Almost All Errands Require a Car', vi: 'Hầu hết việc đi lại cần xe' },
  'detail.bikeParadise': { en: "Biker's Paradise", vi: 'Rất thuận tiện đạp xe' },
  'detail.veryBikeable': { en: 'Very Bikeable', vi: 'Dễ đạp xe' },
  'detail.bikeable': { en: 'Bikeable', vi: 'Có thể đạp xe' },
  'detail.somewhatBikeable': { en: 'Somewhat Bikeable', vi: 'Tạm được cho xe đạp' },
  'detail.goodTransit': { en: 'Good Transit', vi: 'Giao thông công cộng tốt' },
  'detail.someTransit': { en: 'Some Transit', vi: 'Có một số tuyến công cộng' },
  'detail.grades': { en: 'Grades', vi: 'Khối lớp' },
  'detail.showLess': { en: 'Show less', vi: 'Thu gọn' },
  'detail.showAllSchools': { en: 'Show all {count} schools', vi: 'Xem tất cả {count} trường' },
  'detail.recentSales': { en: '{count} recent sales', vi: '{count} giao dịch gần đây' },
  'detail.browseLocalExperts': { en: 'Browse local experts', vi: 'Xem chuyên gia khu vực' },
  'detail.localLegalProtections': { en: 'Local legal protections', vi: 'Bảo vệ pháp lý địa phương' },
  'detail.exploreNearby': { en: 'Explore nearby', vi: 'Khám phá lân cận' },
  'detail.listingLegalUse': { en: 'Listing information is provided for consumers personal, non-commercial use and may not be used for any purpose other than to identify prospective properties consumers may be interested in purchasing.', vi: 'Thông tin tin đăng được cung cấp cho mục đích cá nhân, phi thương mại của người tiêu dùng và chỉ được dùng để xác định các bất động sản mà người tiêu dùng có thể quan tâm mua.' },
  'detail.brokerageDisclosure': { en: 'Listing information is maintained by So Do Van Phuc for internal operation, customer care, and transaction follow-up.', vi: 'Thông tin hồ sơ nhà được Sổ Đỏ Vạn Phúc quản lý để phục vụ vận hành nội bộ, chăm sóc khách hàng và theo dõi giao dịch.' },
  'detail.interested': { en: 'Interested in this property?', vi: 'Bạn quan tâm bất động sản này?' },
  'detail.sidebarContactDesc': { en: 'Get in touch with the listing agent to schedule a tour or make an offer.', vi: 'Liên hệ môi giới đăng tin để đặt lịch xem hoặc đưa ra đề nghị.' },
  'detail.callNow': { en: 'Call now', vi: 'Gọi ngay' },
  'detail.emailAgent': { en: 'Email agent', vi: 'Gửi email cho môi giới' },
  'schedule.requiredFields': { en: 'Please fill in all required fields.', vi: 'Vui lòng điền đầy đủ các trường bắt buộc.' },
  'schedule.viewingRequested': { en: 'Viewing Requested!', vi: 'Đã gửi yêu cầu xem nhà!' },
  'schedule.paymentReceived': { en: "Request received. We'll confirm shortly.", vi: 'Đã nhận yêu cầu. Chúng tôi sẽ xác nhận sớm.' },
  'schedule.another': { en: 'Schedule another', vi: 'Đặt lịch khác' },
  'schedule.fullNamePlaceholder': { en: 'Your full name *', vi: 'Họ và tên *' },
  'schedule.phonePlaceholder': { en: 'Phone number *', vi: 'Số điện thoại *' },
  'schedule.emailPlaceholder': { en: 'Email address *', vi: 'Email *' },
  'schedule.selectDate': { en: 'Select date', vi: 'Chọn ngày' },
  'schedule.selectTime': { en: 'Select time', vi: 'Chọn giờ' },
  'schedule.specialRequests': { en: 'Any special requests (optional)', vi: 'Yêu cầu đặc biệt (không bắt buộc)' },
  'schedule.depositTitle': { en: 'Viewing request', vi: 'Yêu cầu xem nhà' },
  'schedule.depositDesc': { en: 'Send your preferred viewing time. Our team will contact you to confirm.', vi: 'Gửi thời gian muốn xem nhà. Đội ngũ sẽ liên hệ để xác nhận.' },
  'schedule.requestWithDeposit': { en: 'Request viewing', vi: 'Gửi yêu cầu xem nhà' },
  'schedule.paymentFailed': { en: 'Could not send the request. Please try again.', vi: 'Chưa gửi được yêu cầu. Vui lòng thử lại.' },
  'report.submitted': { en: 'Report Submitted', vi: 'Đã gửi báo cáo' },
  'report.thanks': { en: 'Thank you for helping us maintain listing quality.', vi: 'Cảm ơn bạn đã giúp chúng tôi duy trì chất lượng tin đăng.' },
  'report.describeIssue': { en: 'Please describe the issue...', vi: 'Vui lòng mô tả vấn đề...' },
  'report.emailOptional': { en: 'Your email (optional)', vi: 'Email của bạn (không bắt buộc)' },
  'report.genericError': { en: 'Something went wrong. Please try again.', vi: 'Đã xảy ra lỗi. Vui lòng thử lại.' },
  'report.submit': { en: 'Submit Report', vi: 'Gửi báo cáo' },
  'contact.inquirySent': { en: 'Inquiry Sent', vi: 'Đã gửi yêu cầu' },
  'contact.inquirySentDesc': { en: 'Your inquiry has been submitted successfully. We will get back to you soon.', vi: 'Yêu cầu của bạn đã được gửi thành công. Chúng tôi sẽ phản hồi sớm.' },
  'contact.sendAnotherInquiry': { en: 'Send another inquiry', vi: 'Gửi yêu cầu khác' },
};

// ─── Context ─────────────────────────────────────────────────────────
interface LanguageContextType {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'vi',
  setLang: () => {},
  t: (key: string) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() => {
    try {
      const stored = localStorage.getItem('gf_language');
      if (stored === 'vi' || stored === 'en') return stored;
    } catch { /* ignore */ }
    return 'vi';
  });

  const setLang = useCallback((l: Language) => {
    setLangState(l);
    try { localStorage.setItem('gf_language', l); } catch { /* ignore */ }
  }, []);

  const t = useCallback(
    (key: string): string => dict[key]?.[lang] ?? key,
    [lang],
  );

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}


